### ISSUE TITLE
Seems like the imageio uses more memory than needed

### ISSUE THREAD

**Issue by hinerm** [scifio/scifio-imageio#17]
Needed over 3 gigs of memory to convert one plane of a 1.3 GB ome.tiff dataset.

**Comment by phcerdan** [comment]
Seconded. An error sample going out of memory using SCIFIO-ITK bridge.

` terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  /home/phc/Software/ITK/build-devtoolset/Modules/Remote/SCIFIO/src/itkSCIFIOImageIO.cxx:906:
itk::ERROR: SCIFIOImageIO(0xc4b1c0): SCIFIOImageIO: 'SCIFIOITKBridge read' exited abnormally. Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at loci.common.DataTools.allocate(DataTools.java:829)
        at loci.formats.ChannelFiller.openBytes(ChannelFiller.java:183)
        at io.scif.itk.SCIFIOITKBridge.read(SCIFIOITKBridge.java:429)
        at io.scif.itk.SCIFIOITKBridge.executeCommand(SCIFIOITKBridge.java:153)
        at io.scif.itk.SCIFIOITKBridge.executeCommand(SCIFIOITKBridge.java:109)
        at io.scif.itk.SCIFIOITKBridge.waitForInput(SCIFIOITKBridge.java:84)
        at io.scif.itk.SCIFIOITKBridge.executeCommand(SCIFIOITKBridge.java:164)
        at io.scif.itk.SCIFIOITKBridge.main(SCIFIOITKBridge.java:696) `

**Comment by ctrueden** [comment]
I pushed a small performance improvement for reading. But it won't affect the writing performance. There is surely more going on here than just lack of buffer reuse. Best would be to profile of the code on the Java side. @hinerm has mad skills there—but finding the time is another issue...

**Comment by emmenlau** [comment]
I guess this is still relevant? Did somebody follow this up further?
